language: ruby

rvm:
 - 2.5

dist: xenial
os: linux
services:
  - docker

branches:
  only:
    - master
    - /^\d\.\d\.\d(?:-\S*)?$/

before_install:
  - cd ./testing/docker/spectre-mysql
  - docker-compose up -d

jobs:
  include:
    - stage: test
      script:
        - bundle exec rspec spec
        - bundle exec spectre -c testing/spectre/spectre.yml
    - stage: build
      script:
        - bundle exec rspec spec
        - bundle exec spectre -c testing/spectre/spectre.yml
    - stage: deploy
      if: branch =~ /^\d\.\d\.\d(?:-\S*)?$/
      script:
        - bundle exec rake build
        - 'echo -e "---\n:rubygems_api_key: $RUBYGEMS_APIKEY" > ~/.gem/credentials'
        - chmod 0600 ~/.gem/credentials
        - gem push pkg/*.gem
